# Generated by Django 5.1.7 on 2025-04-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('submarca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.IntegerField()),
                ('nombre_solicitante', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('municipio', models.CharField(max_length=50)),
                ('verificentro', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
