# Generated by Django 5.1.7 on 2025-04-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('serie', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('submarca', models.CharField(max_length=50)),
                ('modelo', models.IntegerField()),
                ('nombre_solicitante', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('municipio', models.CharField(max_length=100)),
                ('verificentro', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
