# Generated by Django 5.1.7 on 2025-04-02 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_cita_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('serie', models.CharField(max_length=17, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('submarca', models.CharField(max_length=50)),
                ('modelo', models.IntegerField()),
                ('dueño', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='nombre_solicitante',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='serie',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='submarca',
        ),
        migrations.AlterField(
            model_name='cita',
            name='municipio',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='cita',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.vehiculo'),
        ),
    ]
