# Generated by Django 5.1.7 on 2025-04-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_vehiculo_remove_cita_correo_remove_cita_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='municipio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cita',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='serie',
            field=models.CharField(max_length=30),
        ),
    ]
