# Generated by Django 5.1.7 on 2025-04-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_cita_municipio_alter_cita_vehiculo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='vehiculo',
        ),
    ]
